### ISSUE TITLE
이미지 관리

### ISSUE THREAD

**Issue by pangil5634** [Club-PARD/Bingo_WEB#1]
![파드 배너](https://github.com/Club-PARD/Bingo_WEB/assets/54162245/528910c4-ae7b-44ea-8eef-c9f160b1d932)

![BINGO](https://github.com/Club-PARD/Bingo_WEB/assets/54162245/2d4946d7-8765-4090-b6fa-3bf85baf5502)

**Comment by Cocomong98** [comment]
가릿
